
spring:
  application:
    name: chat-client
  main:
    web-application-type: none
  shell:
    interactive:
      enabled: true
  threads:
    virtual:
      enabled: true
  ai:
    vector-store:
      pgvector:
        initialize-schema: true
    openai:
      api-key: ${OPEN_AI_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash
      embedding:
        embeddings-path: /embeddings
        options:
          model: text-embedding-004
#          model: gemini-embedding-exp-03-07


  #    mcp:
#      client:
#        stdio:
#          connections:
#            filesystem:
#              command: npx
#              args: -y,@modelcontextprotocol/server-filesystem,/Users/pedro.silva/Downloads/test-folder
#        sse:
#          connections:
#            http-mcp-server:
#              url: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost/vector_store
    username: postgres
    password: postgres